@baseURL = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}

# RECADOS
### Lista todos os recados
GET {{baseURL}}/recados/
?limit=10
&offset=0


###Lista apenas um recado
GET {{baseURL}}/recados/27/

###Cria um recado
POST {{baseURL}}/recados/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "CHAMAA",
    "paraId": 20
  }

### Atualiza o Recado
PATCH {{baseURL}}/recados/29/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "Teste de recado atualizado",
    "lido": true
}

###Deleta um Recado
DELETE  {{baseURL}}/recados/29/
Authorization: Bearer {{authToken}}


#






# PESSOAS
### Lista todos as pessoas
GET {{baseURL}}/pessoas/
?limit=10
&offset=10
Authorization: Bearer {{authToken}}

###Lista apenas uma pessoa
GET {{baseURL}}/pessoas/20/
Authorization: Bearer {{authToken}}

###Cria uma pessoa
POST {{baseURL}}/pessoas/
Content-Type: application/json

{
    "email": "TestePolicies123@email.com",
    "password": "123456",
    "nome": "Policies Teste"
}

### Atualiza a pessoa
PATCH {{baseURL}}/pessoas/25/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "nome": "AOOO TCHE TCHE"
}

###Deleta uma pessoa

DELETE  {{baseURL}}/pessoas/25/
Authorization: Bearer {{authToken}}







# AUTH
### Autenticação
# @name authenticate
POST {{baseURL}}/auth/
Content-Type: application/json

{
    "email": "TestePolicies123@email.com",
    "password": "123456"
}


### Re-Autenticação
# @name reAuthenticate
POST {{baseURL}}/auth/refresh/
Content-Type: application/json
{
    "refreshToken": "{{refreshToken}}"
}
