@baseURL = http://localhost:3000

# RECADOS
###
GET {{baseURL}}/recados/

###
GET {{baseURL}}/recados/300/

###
POST {{baseURL}}/recados/
Content-Type: application/json

{
    "recado": "Este é o recado enviado.",
    "Nova chave": "Outro recado"
}

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseURL}}/home/hello

###ExemploDeRota

# @name ExemploDeRota

GET {{baseURL}}/home/exemplo

###ConceitosManualController
# @name ConceitosManualController
GET {{baseURL}}/conceitos-manual

###ConceitosAutomaticoController
# @name ConceitosAutomaticoController
GET {{baseURL}}/conceitos-automatico